spring:
  data:
    mongodb:
      database: countries
      host: 35.165.83.26
      port: 27017
      username: cntr
      password: password

service:
  countryurl: http://services.groupkt.com/country/get/iso2code/